"""Initial ER Diagram Schema

Revision ID: c433fe3b483f
Revises:
Create Date: 2026-02-20 08:16:19.018285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c433fe3b483f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make destructive ops idempotent for environments that never had these objects
    op.execute('DROP INDEX IF EXISTS ix_revenue_id')
    op.execute('DROP TABLE IF EXISTS revenue')
    op.execute('ALTER TABLE distributors DROP COLUMN IF EXISTS contact_name')
    op.execute('ALTER TABLE distributors DROP COLUMN IF EXISTS mobile_phone')
    op.execute('ALTER TABLE distributors DROP COLUMN IF EXISTS branch')
    op.execute('ALTER TABLE distributors DROP COLUMN IF EXISTS address')
    op.execute('ALTER TABLE inventory ADD COLUMN IF NOT EXISTS status VARCHAR')
    op.execute('ALTER TABLE inventory ADD COLUMN IF NOT EXISTS stock INTEGER')
    op.execute('DROP INDEX IF EXISTS ix_inventory_product_id')
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=True)
    op.execute('ALTER TABLE inventory DROP COLUMN IF EXISTS number')
    op.execute('ALTER TABLE orders ADD COLUMN IF NOT EXISTS date TIMESTAMP WITHOUT TIME ZONE')
    op.execute('ALTER TABLE orders ADD COLUMN IF NOT EXISTS distributor_detail_id INTEGER')
    op.execute('ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_price DOUBLE PRECISION')
    op.execute('DROP INDEX IF EXISTS ix_orders_distributor_id')
    op.execute('DROP INDEX IF EXISTS ix_orders_inventory_id')
    op.execute('ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_inventory_id_fkey')
    op.execute('ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_distributor_id_fkey')
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.table_constraints
            WHERE constraint_name = 'orders_distributor_detail_id_fkey'
              AND table_name = 'orders'
        ) THEN
            ALTER TABLE orders
            ADD CONSTRAINT orders_distributor_detail_id_fkey
            FOREIGN KEY (distributor_detail_id)
            REFERENCES distributor_details(id);
        END IF;
    END $$;
    """)
    op.execute('ALTER TABLE orders DROP COLUMN IF EXISTS number')
    op.execute('ALTER TABLE orders DROP COLUMN IF EXISTS inventory_id')
    op.execute('ALTER TABLE orders DROP COLUMN IF EXISTS distributor_id')
    op.execute('ALTER TABLE products ADD COLUMN IF NOT EXISTS cost DOUBLE PRECISION')
    op.alter_column('products', 'price',
                    existing_type=sa.INTEGER(),
                    type_=sa.Float(),
                    existing_nullable=True)
    op.execute('ALTER TABLE products DROP COLUMN IF EXISTS distributor')
    op.execute('ALTER TABLE products DROP COLUMN IF EXISTS status')
    op.execute('ALTER TABLE products DROP COLUMN IF EXISTS batch_number')
    op.execute('ALTER TABLE products DROP COLUMN IF EXISTS stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('batch_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('distributor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('products', 'price',
                    existing_type=sa.Float(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.drop_column('products', 'cost')
    op.add_column('orders', sa.Column('distributor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_distributor_id_fkey', 'orders', 'distributors', ['distributor_id'], ['id'])
    op.create_foreign_key('orders_inventory_id_fkey', 'orders', 'inventory', ['inventory_id'], ['id'])
    op.create_index('ix_orders_inventory_id', 'orders', ['inventory_id'], unique=False)
    op.create_index('ix_orders_distributor_id', 'orders', ['distributor_id'], unique=False)
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'distributor_detail_id')
    op.drop_column('orders', 'date')
    op.add_column('inventory', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.create_index('ix_inventory_product_id', 'inventory', ['product_id'], unique=False)
    op.drop_column('inventory', 'stock')
    op.drop_column('inventory', 'status')
    op.add_column('distributors', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('distributors', sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('distributors', sa.Column('mobile_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('distributors', sa.Column('contact_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('revenue',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('konbini', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('shopee', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('washi', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('arimi', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('airy', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='revenue_pkey')
                    )
    op.create_index('ix_revenue_id', 'revenue', ['id'], unique=False)
    # ### end Alembic commands ###
