"""Initial ER Diagram Schema

Revision ID: c433fe3b483f
Revises:
Create Date: 2026-02-20 08:16:19.018285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c433fe3b483f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_revenue_id', table_name='revenue')
    op.drop_table('revenue')
    op.drop_column('distributors', 'contact_name')
    op.drop_column('distributors', 'mobile_phone')
    op.drop_column('distributors', 'branch')
    op.drop_column('distributors', 'address')
    op.add_column('inventory', sa.Column('status', sa.String(), nullable=True))
    op.add_column('inventory', sa.Column('stock', sa.Integer(), nullable=True))
    op.drop_index('ix_inventory_product_id', table_name='inventory')
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=True)
    op.drop_column('inventory', 'number')
    op.add_column('orders', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('distributor_detail_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=True))
    op.drop_index('ix_orders_distributor_id', table_name='orders')
    op.drop_index('ix_orders_inventory_id', table_name='orders')
    op.drop_constraint('orders_inventory_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_distributor_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'distributor_details', ['distributor_detail_id'], ['id'])
    op.drop_column('orders', 'number')
    op.drop_column('orders', 'inventory_id')
    op.drop_column('orders', 'distributor_id')
    op.add_column('products', sa.Column('cost', sa.Float(), nullable=True))
    op.alter_column('products', 'price',
                    existing_type=sa.INTEGER(),
                    type_=sa.Float(),
                    existing_nullable=True)
    op.drop_column('products', 'distributor')
    op.drop_column('products', 'status')
    op.drop_column('products', 'batch_number')
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('batch_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('distributor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('products', 'price',
                    existing_type=sa.Float(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.drop_column('products', 'cost')
    op.add_column('orders', sa.Column('distributor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_distributor_id_fkey', 'orders', 'distributors', ['distributor_id'], ['id'])
    op.create_foreign_key('orders_inventory_id_fkey', 'orders', 'inventory', ['inventory_id'], ['id'])
    op.create_index('ix_orders_inventory_id', 'orders', ['inventory_id'], unique=False)
    op.create_index('ix_orders_distributor_id', 'orders', ['distributor_id'], unique=False)
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'distributor_detail_id')
    op.drop_column('orders', 'date')
    op.add_column('inventory', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.create_index('ix_inventory_product_id', 'inventory', ['product_id'], unique=False)
    op.drop_column('inventory', 'stock')
    op.drop_column('inventory', 'status')
    op.add_column('distributors', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('distributors', sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('distributors', sa.Column('mobile_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('distributors', sa.Column('contact_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('revenue',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('konbini', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('shopee', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('washi', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('arimi', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('airy', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='revenue_pkey')
                    )
    op.create_index('ix_revenue_id', 'revenue', ['id'], unique=False)
    # ### end Alembic commands ###
